# Server configuration. Thanks to spacecookie, which I basically just copied directly for
# this feature.
[server]
# This can be an IP address or a domain name. I think this feature is *mostly* used for
# filling in the blanks of .gophermap files, but I decided to use this when parsing the
# .gophermap file spec to output complete serve as-is gopher menus (gopher menus must
# include port and host).
hostname = "localhost"
hostPort = 70