name: bore
version: 0.47.0.0
synopsis: Build gopherholes.
description: |
  Static site builder, but for gopherholes. Manage phlogs with tags, use the Markdown renderer and Mustache templating system.
homepage: https://github.com/someodd/bore
bug-reports: https://github.com/someodd/bore/issues
license: GPL-3.0-only
license-file: LICENSE
author: someodd
maintainer: someodd@pm.pm
category: Network
extra-source-files:
  - README.md
  - CHANGELOG.md
tested-with: GHC==9.6.3

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Werror

dependencies:
  - base
  - text
  - filepath-bytestring
  - unix
  - fsnotify
  - tomland
  - xml-conduit-writer
  - parsec
  - data-default
  - xml-conduit
  - word-wrap
  - split
  - fuzzy-dates
  - hourglass
  - bytestring
  - containers
  - mustache
  - filepattern
  - hashmap
  - directory
  - unordered-containers
  - filepath
  - optparse-applicative
  - mtl
  - commonmark
  - frontmatter
  - ansi-wl-pprint
  - commonmark
  - vector
  - time
  - hashable
  - fuzzy-dates
  - hourglass
  - aeson
  - commonmark-extensions
  - yaml
  - Venusia
  - ryvm
  - safe
  - mime-types
  - regex-tdfa
  - regex-compat

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DeriveAnyClass
    - OverloadedRecordDot
    - DuplicateRecordFields
  default-language: GHC2021

executables:
  bore:
    main: Main.hs
    source-dirs: app
    dependencies:
      - bore
    autogen-modules:
      - Paths_bore
    other-modules:
      - Paths_bore
    default-extensions:
      - OverloadedStrings
      - DeriveGeneric
      - DeriveAnyClass
      - OverloadedRecordDot
    default-language: GHC2021

tests:
  bore-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         -Wall -threaded -rtsopts -with-rtsopts=-N
    build-depends:
      - bore
    default-language:    GHC2021