# Server configuration. Thanks to spacecookie, which I basically just copied directly for
# this feature.
[server]
# This can be an IP address or a domain name. I think this feature is *mostly* used for
# filling in the blanks of .gophermap files, but I decided to use this when parsing the
# .gophermap file spec to output complete serve as-is gopher menus (gopher menus must
# include port and host).
hostname = "gopher.someodd.zip"
# Now this actually sets what the server listens on. You can restrict it to a specific
# address or I think even a hostname. The default is "::" which is all addresses.
listenAddress = "::"
# This is the port the server listens on. The default is 70 (I think this is the port the
# Gopher Protocol RFC 1436 specifies).
listenPort = 70
# This is the user the server runs as. This is useful for dropping privileges. The default
# is the user that started the server, so that can be null. Uncomment to define.
user = "bore"